# Generated by Django 4.2 on 2023-04-08 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('cuerpo', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=200)),
                ('posicion', models.CharField(max_length=200)),
                ('numero', models.IntegerField()),
            ],
        ),
    ]
