# Generated by Django 4.2 on 2023-04-08 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_rutina', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='rutina',
            new_name='t_rutina',
        ),
    ]
