# Generated by Django 4.2 on 2023-04-08 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_rutina', '0002_rename_rutina_t_rutina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_rutina',
            name='cuerpo',
        ),
    ]
