# Generated by Django 4.2 on 2023-04-08 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rutina', '0003_remove_t_rutina_cuerpo'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_cuerpo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuerpo', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='t_rutina',
            new_name='t_ejercicio',
        ),
    ]
