# Generated by Django 4.2 on 2023-04-08 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_rutina', '0004_t_cuerpo_rename_t_rutina_t_ejercicio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_ejercicio',
            old_name='nombre',
            new_name='ejercicio',
        ),
        migrations.RenameField(
            model_name='t_ejercicio',
            old_name='numero',
            new_name='repeticiones',
        ),
        migrations.AddField(
            model_name='t_ejercicio',
            name='cuerpo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app_rutina.t_cuerpo'),
            preserve_default=False,
        ),
    ]
